"""add_category_id_for_bot

Revision ID: 20241127040939
Revises: 20241127024036
Create Date: 2024-11-27 04:09:40.523015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20241127040939"
down_revision: Union[str, None] = "20241127024036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bots", sa.Column("category_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "bots", "mst_items", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bots", type_="foreignkey")
    op.drop_column("bots", "category_id")
    # ### end Alembic commands ###
