"""add_master_data

Revision ID: 20241127012047
Revises: 20241126025623
Create Date: 2024-11-27 01:20:48.511138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20241127012047"
down_revision: Union[str, None] = "20241126025623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mst_categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        op.f("ix_mst_categories_created_by"),
        "mst_categories",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mst_categories_deleted_at"),
        "mst_categories",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "mst_items",
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["mst_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_category_id_name", "mst_items", ["category_id", "name"], unique=False
    )
    op.create_index(
        op.f("ix_mst_items_created_by"), "mst_items", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_mst_items_deleted_at"), "mst_items", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mst_items_deleted_at"), table_name="mst_items")
    op.drop_index(op.f("ix_mst_items_created_by"), table_name="mst_items")
    op.drop_index("idx_category_id_name", table_name="mst_items")
    op.drop_table("mst_items")
    op.drop_index(op.f("ix_mst_categories_deleted_at"), table_name="mst_categories")
    op.drop_index(op.f("ix_mst_categories_created_by"), table_name="mst_categories")
    op.drop_table("mst_categories")
    # ### end Alembic commands ###
