"""init

Revision ID: 20241126025623
Revises: 
Create Date: 2024-11-26 02:56:23.659850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20241126025623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('greeting', sa.Text(), nullable=True),
    sa.Column('is_bot_definition_public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED', 'DELETED', 'PENDING', name='statusenum'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_created_by'), 'bots', ['created_by'], unique=False)
    op.create_index(op.f('ix_bots_deleted_at'), 'bots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bots_tenant_id'), 'bots', ['tenant_id'], unique=False)
    op.create_table('bot_configs',
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_created_by'), 'bot_configs', ['created_by'], unique=False)
    op.create_index(op.f('ix_bot_configs_deleted_at'), 'bot_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bot_configs_tenant_id'), 'bot_configs', ['tenant_id'], unique=False)
    op.create_table('config_variables',
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['bot_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_variables_created_by'), 'config_variables', ['created_by'], unique=False)
    op.create_index(op.f('ix_config_variables_deleted_at'), 'config_variables', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_config_variables_tenant_id'), 'config_variables', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_variables_tenant_id'), table_name='config_variables')
    op.drop_index(op.f('ix_config_variables_deleted_at'), table_name='config_variables')
    op.drop_index(op.f('ix_config_variables_created_by'), table_name='config_variables')
    op.drop_table('config_variables')
    op.drop_index(op.f('ix_bot_configs_tenant_id'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_deleted_at'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_created_by'), table_name='bot_configs')
    op.drop_table('bot_configs')
    op.drop_index(op.f('ix_bots_tenant_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_deleted_at'), table_name='bots')
    op.drop_index(op.f('ix_bots_created_by'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
