"""table_bot

Revision ID: 20250106150800
Revises: 20250106144710
Create Date: 2025-01-06 15:08:01.921287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250106150800'
down_revision: Union[str, None] = '20250106144710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
