"""team_bots

Revision ID: 20250101131911
Revises: 20241127040939
Create Date: 2025-01-01 13:19:12.460081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250101131911'
down_revision: Union[str, None] = '20241127040939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_bot_access',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'bot_id', name='unique_team_bot')
    )
    op.create_index(op.f('ix_team_bot_access_created_by'), 'team_bot_access', ['created_by'], unique=False)
    op.create_index(op.f('ix_team_bot_access_deleted_at'), 'team_bot_access', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_team_bot_access_tenant_id'), 'team_bot_access', ['tenant_id'], unique=False)
    op.add_column('bots', sa.Column('team_id', sa.UUID(), nullable=True))
    op.add_column('bots', sa.Column('access_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'access_level')
    op.drop_column('bots', 'team_id')
    op.drop_index(op.f('ix_team_bot_access_tenant_id'), table_name='team_bot_access')
    op.drop_index(op.f('ix_team_bot_access_deleted_at'), table_name='team_bot_access')
    op.drop_index(op.f('ix_team_bot_access_created_by'), table_name='team_bot_access')
    op.drop_table('team_bot_access')
    # ### end Alembic commands ###
