"""table_bot

Revision ID: 20250106144710
Revises: 20250101131911
Create Date: 2025-01-06 14:47:11.145844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250106144710'
down_revision: Union[str, None] = '20250101131911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bot_configs_deleted_at', table_name='bot_configs')
    op.drop_index('ix_bot_configs_tenant_id', table_name='bot_configs')
    op.drop_column('bot_configs', 'deleted_by')
    op.drop_column('bot_configs', 'deleted_at')
    op.drop_column('bot_configs', 'tenant_id')
    op.drop_index('ix_config_variables_deleted_at', table_name='config_variables')
    op.drop_index('ix_config_variables_tenant_id', table_name='config_variables')
    op.drop_column('config_variables', 'tenant_id')
    op.drop_column('config_variables', 'deleted_at')
    op.drop_column('config_variables', 'deleted_by')
    op.drop_index('ix_team_bot_access_deleted_at', table_name='team_bot_access')
    op.drop_index('ix_team_bot_access_tenant_id', table_name='team_bot_access')
    op.drop_column('team_bot_access', 'tenant_id')
    op.drop_column('team_bot_access', 'deleted_at')
    op.drop_column('team_bot_access', 'deleted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_bot_access', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('team_bot_access', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('team_bot_access', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_team_bot_access_tenant_id', 'team_bot_access', ['tenant_id'], unique=False)
    op.create_index('ix_team_bot_access_deleted_at', 'team_bot_access', ['deleted_at'], unique=False)
    op.add_column('config_variables', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('config_variables', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('config_variables', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_config_variables_tenant_id', 'config_variables', ['tenant_id'], unique=False)
    op.create_index('ix_config_variables_deleted_at', 'config_variables', ['deleted_at'], unique=False)
    op.add_column('bot_configs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('bot_configs', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bot_configs', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_bot_configs_tenant_id', 'bot_configs', ['tenant_id'], unique=False)
    op.create_index('ix_bot_configs_deleted_at', 'bot_configs', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
